### ISSUE TITLE
Read-write support

### ISSUE THREAD

**Issue by Cliffsky** [libyal/libfvde#26]
hello, 

does libfvde support write operations on filevaulted drives?

**Comment by joachimmetz** [comment]
No

**Comment by nihilus** [comment]
Any hints on when this might be available? I need to run fsck before mounting the filesystem wrapped in the Filevault which makes the whole thing unusable for now.

**Comment by joachimmetz** [comment]
> Any hints on when this might be available?

This is a very low priority on my list, also I'm wondering if the library should have write support, since it makes things far more complex.

> I need to run fsck before mounting the filesystem wrapped in the Filevault which makes the whole thing unusable for now.

Why, can't you can use e.g. xmount with a cache file on top of the fvde mounted device? And emulate write support without actually writing to the original data.

**Comment by nihilus** [comment]
> > Any hints on when this might be available?
> 
> This is a very low priority on my list, also I'm wondering if the library should have write support, since it makes things far more complex.
> 
> > I need to run fsck before mounting the filesystem wrapped in the Filevault which makes the whole thing unusable for now.
> 
> Why, can't you can use e.g. xmount with a cache file on top of the fvde mounted device? And emulate write support without actually writing to the original data.

Great idea! I will give it try before buying a 2nd disk.
