### ISSUE TITLE
How to access removable CoreStorage FVDE encrypted disk?

### ISSUE THREAD

**Issue by miguelmorin** [libyal/libfvde#60]
I would like to use `fvde` to show the password hint of a backup drive I encrypted. I read the paper "Infiltrate the Vault" from the author and, if I understand correctly, the hint is stored in a `Recovery HD` volume, next to the main `Macintosh HD` volume. When I run `diskutil list` with the encrypted drive connected, I see:

```
$ diskutil list
...
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:          Apple_CoreStorage Time Machine Encryped   239.7 GB   disk2s2
   3:                 Apple_Boot Boot OS X               134.2 MB   disk2s3
```

That `Recovery HD` is present in the startup disk and is absent from the external encrypted backup.

When Disk Utility encrypts a drive with File Vault 2, does it create a recovery volume with the password hint in a similar way to a startup volume, and so could one use `fvde` to extract it?

**Comment by joachimmetz** [comment]
FVDE is CoreStorage not APFS

**Comment by miguelmorin** [comment]
Thank you Joachim for the quick reply. I wonder if there's a confusion: the APFS Volume in the list is not the one I want to access. I want to access the `Apple_CoreStorage`, with name `Time Machine Encrypted` in that list. It was formatted with `Disk Utility` on `macOS Yosemite` with format `Mac OS Extended (Journaled, Encrypted)` format. Could you confirm if this encryption is not compatible with `libfvde`?

**Comment by joachimmetz** [comment]
assuming question was answered, closing issue

**Comment by mm3509** [comment]
Hi again! Sorry for the delay, I got very busy with work, but can now focus on this. I got a Linux machine and installed from APT. I found the `EncryptedRoot.plist` of a drive well hidden in nested folders, which is very good news. When I run `fvdeinfo`, it does not show details from the XML file. Because I installed from a package, I did not compile with the flags to enable verbose and debug output, so I tried `-v -v` to show output, but it only shows an error. I paste the command logs below. Is it possible to get more information from the hard drive's encrypted plist with fvdeinfo?

```
$ sudo mount -t hfsplus /dev/sdc3 /mnt/mac_recovery
$ ls -laht /mnt/mac_recovery/Backups.backupdb/.RecoverySets/0/
total 22M
drwxr-xr-x 1 root root   13 Dec 31  2017 .
drwxr-xr-x 1 root root    3 Dec 31  2017 ..
-rw-r--r-- 1 root root 2.7K Dec 31  2017 EncryptedRoot.plist.wipekey
...
$ sudo fvdeinfo -v -v -e /mnt/mac_recovery/Backups.backupdb/.RecoverySets/0/EncryptedRoot.plist.wipekey /dev/sdc2
fvdeinfo 20190104

Unable to unlock keys.
```
